# Generated by Django 4.2 on 2024-12-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=100)),
                ('price', models.IntegerField(verbose_name='price')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='course_image')),
            ],
        ),
    ]
