# Generated by Django 4.2 on 2025-01-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_course_stars_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='price'),
        ),
    ]
