# Generated by Django 4.2 on 2025-01-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_course_price_alter_course_students_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='course_item'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='students_number'),
        ),
    ]
