# Generated by Django 4.2 on 2025-01-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_course_picture_alter_course_students_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('category', models.CharField(max_length=200, verbose_name='lecture_name')),
                ('picture', models.ImageField(upload_to='lecturer_pic', verbose_name='picture')),
            ],
        ),
    ]
