# Generated by Django 4.2 on 2025-01-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_lecturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('level', models.CharField(max_length=200, verbose_name='level')),
                ('picture', models.ImageField(upload_to='message_pic', verbose_name='picture')),
                ('message', models.TextField(verbose_name='message')),
            ],
        ),
    ]
