# Generated by Django 4.2 on 2024-09-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس محصول')),
                ('description', models.ImageField(blank=True, null=True, upload_to='', verbose_name='توضیحات')),
            ],
        ),
    ]
