# Generated by Django 4.2 on 2024-09-10 20:06

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=9832, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='دسته بندی'),
            preserve_default=False,
        ),
    ]
