# Generated by Django 4.2 on 2024-09-13 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accounts_profile_picture'),
        ('selling', '0002_product_price_product_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200, verbose_name='shop_name')),
                ('address', models.CharField(max_length=300, verbose_name='address')),
                ('email', models.EmailField(max_length=254, verbose_name='shop_email')),
                ('footer_brief_slogan', models.CharField(max_length=200, verbose_name='shop_footer_brief_slogan')),
                ('footer_slogan', models.CharField(max_length=400, verbose_name='footer_slogan')),
                ('footer_slogan_description', models.TextField(max_length=500, verbose_name='footer_slogan_descrition')),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_in_shop', to='accounts.accounts')),
            ],
        ),
    ]
