# Generated by Django 4.2 on 2024-09-16 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accounts_profile_picture'),
        ('selling', '0003_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.CreateModel(
            name='home_pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan_number', models.IntegerField(default=2041, verbose_name='home_slogan_number')),
                ('slogan_part', models.CharField(max_length=100, verbose_name='home_slogan')),
                ('goal_number', models.IntegerField(default=2042, verbose_name='home_slogan_number')),
                ('goal_part', models.CharField(max_length=100, verbose_name='home_slogan')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_in_home_page', to='accounts.accounts')),
            ],
        ),
    ]
