# Generated by Django 4.2 on 2024-09-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0004_alter_product_description_home_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='feature_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام ویژگی')),
                ('amount', models.CharField(max_length=50, verbose_name='میزان یا تعداد ویژگی')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(to='selling.feature_table', verbose_name='ویژگی ها'),
        ),
    ]
