# Generated by Django 4.2 on 2024-09-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='profile_picture'),
        ),
    ]
